### PR TITLE
Modularize the transfer of initiality

### PR DESCRIPTION
**Pull request by benediktahrens**
@amblafont : what is the difference between `PresentableSignature_to_signature_2` and `PresentableSignature_to_signature`?

### CODE REVIEW

**Comment by amblafont** [comment]
Well... According to the history, it seems that you are the author of `PresentableSignature_to_signature_2` :)

**Comment by benediktahrens** [comment]
@amblafont : they don't seem to do the same thing, since replacing _2 by the other one does not work. Can you explain the difference?

**Comment by amblafont** [comment]
Oops sorry. The first one is the obvious coercion. The second one transforms the arity (a, Theta^(n)) into the arity (a x Theta^n, Theta) for each (a, Theta^(n)) of the presentable signature

**Comment by benediktahrens** [comment]
On 07/02/18 10:38, Ambroise wrote:
> Oops sorry. The first one is the obvious coercion. The second one 
> transforms the arity (a, Theta^(n)) into the arity (a x Theta^n, Theta) 
> for each (a, Theta^(n)) of the presentable signature

So a better name for the second one would be something like
`PresentableSignature_to_RawSignature`?

**Comment by amblafont** [comment]
Oh yes that would be better, although a raw signature is defined somewhere as a a list of half-arities I guess

**Comment by benediktahrens** [comment]
On 07/02/18 10:46, Ambroise wrote:
> Oh yes that would be better, although a raw signature is defined 
> somewhere as a a list of half-arities I guess

Right, so another name would be better.
How about `Rawify_PresentableSignature`?

**Comment by amblafont** [comment]
good ! Maybe it could be split in two steps ?

**Comment by benediktahrens** [comment]
On 07/02/18 10:59, Ambroise wrote:
> good ! Maybe it could be split in two steps ?

What do you mean by that? What is "it"? What are the two steps?

**Comment by amblafont** [comment]
I notice that there are two lemmas that have the same name `initial_presentable_raw_sig` : one in PresentableSig.v and one in PresentableRawSig.v. I suggest renaming the one in PresentableSig into `initial_presentable_sig`, what do you think ?

The first step would be to gather the list of half arities as a `RawSigToHAr.rawSig`, and the second step would use `RawSigToHar.rawSigToSig` to get the full signature

**Comment by benediktahrens** [comment]
On 07/02/18 12:01, Ambroise wrote:
> I notice that there are two lemmas that have the same name 
> |initial_presentable_raw_sig| : one in PresentableSig.v and one in 
> PresentableRawSig.v. I suggest renaming the one in PresentableSig into 
> |initial_presentable_sig|, what do you think ?

I like the idea, except for capitalization: since the type of initial 
objects is called `Initial`, how about |Initial_PresentableSig| ?
And similar for the other.

> 
> The first step would be to gather the list of half arities as a 
> |RawSigToHAr.rawSig|, and the second step would use 
> |RawSigToHar.rawSigToSig| to get the full signature

I don't like the vocabulary. Why is a family of half-arities not called 
half-signature? But that is a different topic.


In general, there should be maps in as many of the directions as 
possible, and they should be suitably composed whenever needed.

I agree with your specific suggestion and encourage you to find a 
systematic way to convert between different notions of signature.

**Comment by benediktahrens** [comment]
@amblafont : Can we merge this PR?

**Pull request merged**
