### PR TITLE
A faithful fibration projection lifts equalizers

### PR DESCRIPTION
**Pull request by amblafont**
This is not exactly what is proven : what is proven is that if the image of the diagram has an equalizer, then the equalizer exists in the total cat. Trying to use the general definition of creation of limits has been proved very tedious

### CODE REVIEW

**Comment by amblafont** [comment]
I made some English fautes above. Do you know how to correct them?

**Comment by benediktahrens** [comment]
As you say, the result you show is not exactly "creation of equalizers". However, proving creation of equalizers should be easy: the only part that is missing is the uniqueness of the cone above. But uniqueness is easy, because the fibration is faithful. So maybe it is worth doing this. The proofs that are already there can be reused entirely, I think.

Rewriting the commit message is described in https://help.github.com/articles/changing-a-commit-message/ , but I do not think that it is necessary.

**Comment by amblafont** [comment]
We know that there is a colimiting cone above a colimiting cone. As a colimit, we already know it is unique, no? I don't understand why faithfulness would be necessary here

**Comment by benediktahrens** [comment]
The definition of creating limits includes that there is a *unique cone* 
above the limiting cone.

**Comment by amblafont** [comment]
After discussion by mails, it may be more about lifting limits than creating them

**Pull request merged**
