### PR TITLE
make compile with latest unimath and typetheory

### PR DESCRIPTION
**Pull request by benediktahrens**
- temporarily admit a proof, which I don't know how to fix

### CODE REVIEW

**Comment by amblafont** [comment]
lgtm except some parts that do not respect the guidelines specified in the README

**Comment by benediktahrens** [comment]
On 06/28/2017 02:58 PM, Ambroise wrote:
> lgtm except some parts that do not respect the guidelines specified in
> the README

Maybe you can correct those parts?

**Comment by amblafont** [comment]
je rigole, y a rien dans le README :)

**Comment by benediktahrens** [comment]
On 06/28/2017 03:08 PM, Ambroise wrote:
> je rigole, y a rien dans le README :)
> 

Tu te moques de UniMath ?

**Comment by amblafont** [comment]
pas particulièrement, j'ai des pbs aussi avec ma PR dans coq

**Pull request merged**
