### PR TITLE
The fibration of 2-models over 2-signatures

### PR DESCRIPTION
**Pull request by amblafont**

### CODE REVIEW

**Comment by benediktahrens** [comment]
@amblafont : Is this PR still of interest?

**Comment by amblafont** [comment]
why not?

**Comment by benediktahrens** [comment]
On 21/09/2018 11:48, Ambroise wrote:
> why not?

I wasn't sure, that's all.
There are still a few admitted results in the PR. Once these are fixed, 
we can merge.

**Comment by benediktahrens** [comment]
The category 2Sig should be defined as the total category of a displayed category (which is easy to define). This is shorter and useful for showing that the forgetful functor 2Sig -> Sig is an op-fibration.

**Pull request merged**
